import os
import time
import random
import string
import json
import urllib.request
from urllib.error import URLError, HTTPError

# Configurable via environment variable API_BASE_URL
BASE_URL = os.getenv("API_BASE_URL", "http://localhost:8000")

def random_string(length=8):
    return ''.join(random.choices(string.ascii_lowercase, k=length))

def make_request(method, path, data=None):
    """Helper to perform HTTP requests without relying on external packages like 'requests'."""
    url = f"{BASE_URL}{path}"
    headers = {'Content-Type': 'application/json', 'Accept': 'application/json'}
    
    data_bytes = None
    if data is not None:
        data_bytes = json.dumps(data).encode('utf-8')
        
    req = urllib.request.Request(url, data=data_bytes, headers=headers, method=method)
    try:
        with urllib.request.urlopen(req) as response:
            res_str = response.read().decode('utf-8')
            return response.status, json.loads(res_str) if res_str else {}
    except HTTPError as e:
        try:
            error_body = json.loads(e.read().decode('utf-8'))
        except Exception:
            error_body = {"detail": str(e)}
        return e.code, error_body
    except URLError as e:
        print(f"Connection error to {url}: {e.reason}")
        return None, None

def run_simulation():
    print(f"Starting activity simulation against {BASE_URL}")
    print("Press Ctrl+C to stop.\n")
    
    users = []
    posts = []
    
    # Attempt to fetch existing state to avoid inserting fully blind
    status, res_data = make_request("GET", "/users")
    if status == 200 and isinstance(res_data, list):
        users.extend([u['id'] for u in res_data])
        print(f"[*] Discovered {len(users)} existing users in DB.")
        
    status, res_data = make_request("GET", "/posts/recent")
    if status == 200 and isinstance(res_data, list):
        posts.extend([p['id'] for p in res_data])
        print(f"[*] Discovered {len(posts)} existing recent posts.")
    
    print("\n--- Generating Activity ---")
    while True:
        try:
            # Action probabilities: 10% new user, 30% new follow, 20% new post, 40% new like
            action = random.choices(
                ['new_user', 'new_follow', 'new_post', 'new_like'],
                weights=[0.1, 0.3, 0.2, 0.4],
                k=1
            )[0]
            
            # Force creating a user if none / not enough exist
            if action == 'new_user' or len(users) < 2:
                user_data = {
                    "username": f"user_{random_string(5)}",
                    "email": f"{random_string(5)}@example.com",
                    "bio": "I am a simulated user generated by the script!"
                }
                status, res = make_request("POST", "/users", data=user_data)
                if status == 200:
                    new_id = res.get('id')
                    if new_id:
                        users.append(new_id)
                        print(f"[NEW USER] Created {user_data['username']} (ID: {new_id})")
                elif status is not None:
                    print(f"[NEW USER FAILED] {status} - {res}")
                        
            elif action == 'new_follow' and len(users) >= 2:
                user_id = random.choice(users)
                follower_id = random.choice(users)
                
                # Ensure they don't follow themselves
                attempts = 0
                while follower_id == user_id and attempts < 10:
                    follower_id = random.choice(users)
                    attempts += 1
                
                if follower_id != user_id:
                    status, res = make_request("POST", f"/users/{user_id}/follow", data={"follower_id": follower_id})
                    if status == 200:
                        print(f"[NEW FOLLOW] User {follower_id} is now following User {user_id}")
                        
            elif action == 'new_post' and users:
                user_id = random.choice(users)
                post_data = {
                    "user_id": user_id,
                    "title": f"Simulated Post {random_string(4)}",
                    "text": "This is automatically generated content! " + random_string(15)
                }
                status, res = make_request("POST", "/posts", data=post_data)
                if status == 200:
                    new_post_id = res.get('id')
                    if new_post_id:
                        posts.append(new_post_id)
                        print(f"[NEW POST] User {user_id} published post {new_post_id}")
                        
            elif action == 'new_like' and posts and users:
                post_id = random.choice(posts)
                user_id = random.choice(users)
                status, res = make_request("POST", f"/posts/{post_id}/like", data={"user_id": user_id})
                if status == 200:
                    print(f"[NEW LIKE] User {user_id} liked post {post_id}")
            
            # Wait 1-3 seconds between actions so we don't spam instantly
            time.sleep(random.uniform(1.0, 3.0))
            
        except KeyboardInterrupt:
            break
        except Exception as e:
            print(f"Error during simulation step: {e}")
            time.sleep(2)

if __name__ == "__main__":
    try:
        run_simulation()
    except KeyboardInterrupt:
        print("\nSimulation stopped manually.")
